branch-defaults:
  lesson-2-exercise-1:
    environment: test3-dev8
    group_suffix: null
environment-defaults:
  Test3-env:
    branch: null
    repository: null
global:
  application_name: test3
  branch: null
  default_ec2_keyname: lesson-2-exercise-1
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
